### ISSUE TITLE
Support Order Scraping

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#136]
We want to make it easy for someone like Gem to get all relevant orders from our system for ingestion. This has two potential parts to it:

1) They will likely want a way to filter out open sea orders, which they are already getting. I feel like our solution for sources could use some work, but maybe we can create an option to `excludeSource` and if you pass open sea's address, it will exclude them

2) They also need to be able to paginate efficiently through all orders. This might be a good candidate for our first API to utilize keyset pagination

**Comment by georgeroman** [comment]
This should be done, the new API is called `/orders/all`:
- https://indexer-v3-2-mainnet.up.railway.app/orders/all?side=sell&limit=1000&continuation=1643216389130_0xc421ee1a900dc0f80ebeeec6b2ca5316160cf68358d780275af9adeaecf52f2e&sortDirection=asc
- https://indexer-v3-2-mainnet.up.railway.app/orders/all?side=buy&limit=1000&continuation=1643216389130_0xc421ee1a900dc0f80ebeeec6b2ca5316160cf68358d780275af9adeaecf52f2e&sortDirection=asc
