### ISSUE TITLE
Order source

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#148]
- When publishing an order (to both the Indexer and Arweave), an optional "source" field can be passed, which is an ethereum address
- This address should be owned by the source, as it is where future rewards may be sent
- Because this field is not universally set, the Indexer ultimately needs to decide what the source is, based on its own logic
- For example, for any order that set the fee recipient to Open Sea's address, the source would be Open Sea, irregardless of the source that was passed 
- Similarly, the source fee is deduced by Indexer. Based on the source address, and the details of the order, it can have logic to determine what was fees, and what was royalties
- In the future, we may need mitigations against malicious relayers who front run orders and change the source, but it's not worth worrying about now. Most likely we will need some sort of whitelist for relayers who are more reliable, or a way for the true source to build their address into the signed order

**Comment by ptrwtts** [comment]
It might also make sense to handle the destination where items are filled from too. Is this possible, or do we need router for this?

**Comment by georgeroman** [comment]
This should be done on the old indexer, the /execute/list and /execute/bid APIs now take an additional source parameter which will be included in the order data that will be posted to the orderbook.
