### ISSUE TITLE
More responsive Ethereum indexing

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#154]
Right now we poll Ethereum for new data, which can lead to delays of up to X-1 for a poll frequency of X. This isn't great for real-time UX. Here's a proposed alternative design:

- Subscribe to the new block websocket, and trigger event fetching as soon as a new block comes in
- Every 5 seconds, see if it's been longer than 15 seconds without a new block, and directly check for new blocks. This acts as a redundancy in case we miss a websocket event

**Comment by georgeroman** [comment]
This should be done - I've left all the previous logic as it is (which will act as a redundancy check for missed events or in case the websocket subscription gets dropped), but new events should now be available right after the provider notifies us of new blocks.
