### ISSUE TITLE
New Indexer Errors

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#175]
Validation

- https://api.reservoir.tools/orders/v1?token=0x521f9c7505005cfa19a8e5786a9c3c9c9f5e6f42:148
- https://api.reservoir.tools/users/0x51845fad9e2afbc9f6f07cfd60fdba45df1e3c2d/collections/v1

Timeout / Slow

- https://api.reservoir.tools/users/0x51845fad9e2afbc9f6f07cfd60fdba45df1e3c2d/tokens/v1

**Comment by georgeroman** [comment]
These should all be fixed. As part of it, I changed all count values to get returned as strings instead of (possibly overflowing) numbers.
