### ISSUE TITLE
slow query: collections/v1 (without filters)

### ISSUE THREAD

**Issue by dikkeduif** [reservoirprotocol/indexer-v3#190]
The average response times for collections/v1 are around 10 seconds, unless you filter by community or contract

```
curl --request GET \
  --url 'https://api.reservoir.tools/collections/v1?sortBy=allTimeVolume'
```

Visualisations:
https://explain.dalibo.com/plan/xLB

https://app.datadoghq.com/databases?query=host%3Acontainers-us-west-29.railway.app%20collections&dbPanels=%5B%7B%22t%22%3A%22dbQueryPanel%22%2C%22qs%22%3A%2232150381eb9b70da%22%2C%22dbType%22%3A%22PostgreSQL%22%7D%5D&dbType=PostgreSQL&sort=avgLatency%3Adesc&start=1646560611201&end=1646564211201&paused=false

Template
```
WITH x 
SELECT c . id, c . slug, c . name, c . metadata, c . royalties, c . token_set_id, c . token_count, ( 
    SELECT MIN ( t . floor_sell_value ) 
    FROM tokens t 
    WHERE t . collection_id = ? . id 
), c . day1_rank, c . day1_volume, c . day7_rank, c . day7_volume, c . day30_rank, c . day30_volume, c . all_time_rank, c . all_time_volume 
FROM collections c 
    JOIN tokens t ON c . id = ? . collection_id 
GROUP BY c . id 
ORDER BY c . all_time_volume DESC OFFSET ? 
LIMIT ? 
) 
SELECT x . *, y . * 
FROM x 
    LEFT JOIN LATERAL ( 
    SELECT ts . top_buy_value, ts . top_buy_maker 
    FROM token_sets ts 
    WHERE ts . id = ? . token_set_id 
    ORDER BY ts . top_buy_value DESC 
    LIMIT ? 
) y ON ?
```

Example
```
WITH "x" AS (
        SELECT
          "c"."id",
          "c"."slug",
          "c"."name",
          "c"."metadata",
          "c"."royalties",
          "c"."token_set_id",
          "c"."token_count",
          (
            SELECT MIN("t"."floor_sell_value") FROM "tokens" "t"
            WHERE "t"."collection_id" = "c"."id"
          ) AS "floor_sell_value",
          "c"."day1_rank",
          "c"."day1_volume",
          "c"."day7_rank",
          "c"."day7_volume",
          "c"."day30_rank",
          "c"."day30_volume",
          "c"."all_time_rank",
          "c"."all_time_volume"
        FROM "collections" "c"
        JOIN "tokens" "t"
          ON "c"."id" = "t"."collection_id"
        GROUP BY c.id
       ORDER BY "c"."all_time_volume" DESC
        OFFSET 0 LIMIT 20)
        SELECT
          "x".*,
          "y".*
        FROM "x"
        LEFT JOIN LATERAL (
          SELECT
            "ts"."top_buy_value",
            "ts"."top_buy_maker"
          FROM "token_sets" "ts"
          WHERE "ts"."id" = "x"."token_set_id"
          ORDER BY "ts"."top_buy_value" DESC
          LIMIT 1
        ) "y" ON TRUE
```

The problem is with the additional all_time_volume, and day1_volume columns that were added for sorting. As soon as we remove `ORDER BY "c"."all_time_volume" DESC` we get fast results. 

Possible solutions:

I have not tried adding additional indexes, but I think we can optimize the query overall and skip the join on tokens and remove the `SELECT MIN("t"."floor_sell_value") FROM "tokens" "t"`.

As a suggestion we can do the following:
- Add an extra column in collections called `min_floor_sell_value`
- Whenever we get new values in the tokens table, recalculate the `min_floor_sell_value` for that collection and update the collections `min_floor_sell_value` field (we can do it either inline or in a job, whatever makes sense)
- Add an admin endpoint that allows us to recalculate all the collections' `min_floor_sell_value` fields and update the corresponding collections.
- As an added feature, we can add a sorting index on `min_floor_sell_value` and make it a sorting filter

The query would look like this
```
WITH "x" AS (
        SELECT
          "c"."id",
          "c"."slug",
          "c"."name",
          "c"."metadata",
          "c"."royalties",
          "c"."token_set_id",
          "c"."token_count",
          "c"."day1_rank",
          "c"."day1_volume",
          "c"."day7_rank",
          "c"."day7_volume",
          "c"."day30_rank",
          "c"."day30_volume",
          "c"."all_time_rank",
          "c"."all_time_volume",
          "c"."min_floor_sell_value" <== after removal of the MIN/GROUP BY on tokens
        FROM "collections" "c"
        GROUP BY c.id
       ORDER BY "c"."all_time_volume" DESC
        OFFSET 0 LIMIT 20)
        SELECT
          "x".*,
          "y".*
        FROM "x"
        LEFT JOIN LATERAL (
          SELECT
            "ts"."top_buy_value",
            "ts"."top_buy_maker"
          FROM "token_sets" "ts"
          WHERE "ts"."id" = "x"."token_set_id"
          ORDER BY "ts"."top_buy_value" DESC
          LIMIT 1
        ) "y" ON TRUE
```

**Comment by dikkeduif** [comment]
The join on tokens was already removed by @georgeroman improving results! We might want to still move the floor_sell_value to a column inside the collections

**Comment by georgeroman** [comment]
Closing this as it seems the API is quite efficient for now.
