### ISSUE TITLE
Optimize Slow Queries

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#192]
In V5, we added support for ALL nfts, which resulted in much larger tables. As a result, some APIs that previously ran fine slowed to a crawl, because they evidently weren't properly indexed. We want to fix them ASAP. In some cases, it will be a case of tweaking the indexes. In other cases, we might need to change the underlying tables or API itself.

**Known Slow APIs**

- [User Tokens](https://api.reservoir.tools/users/0xf296178d553c8ec21a2fbd2c5dda8ca9ac905a00/tokens/v1)
- [User Collections](https://api.reservoir.tools/users/0xf296178d553c8ec21a2fbd2c5dda8ca9ac905a00/collections/v1)
- [All Collections](https://api.reservoir.tools/collections/v1)

**Comment by georgeroman** [comment]
`All Collections` is now fixed, there was an irrelevant join that slowed it down.

**Comment by ipeleg** [comment]
`User Tokens` Updated to V2.

Reopening this as `User Collections` still need to be modified and will be updated next
