### ISSUE TITLE
Collection ID should be case insensitive

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#195]
All APIs with collection id need to be updated

**Comment by georgeroman** [comment]
This is fixed: https://api.reservoir.tools/tokens/details/v1?collection=0xa7d8d9ef8D8Ce8992Df33D8b8CF4Aebabd5bD270:78000000:78999999&onSale=true&sortBy=floorAskPrice&sortDirection=desc&offset=0&limit=20
