### ISSUE TITLE
Updated response for sales API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#196]
- Include the type of order (ask or bid)
- Instead of maker/taker, return to/from. This is usually what people want to know, and maker/taker can be derived from this and the type

This update should be versioned!

**Comment by georgeroman** [comment]
This is done: https://api.reservoir.tools/sales/v2?contract=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d
