### ISSUE TITLE
Optimize tokens APIs

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#203]
For both tokens and tokens/details APIs:

- Get rid of the token id sort option
- Get rid of onSale filter
- Get rid of sortDirection (floorSell always ASC, topBid always DESC NULLS LAST)
- Sort options (floorSell and topBid) only allowed when filtering by collection / attribute
- When filtering by contract, it should always sort by token_id
- Delete indexes on `contract + floorSell/topBuy`. We are no longer supporting price sorting on contracts.
- Switch to continuation pagination. For this, we will likely need to add `token_id` to the indexes after `floorSell` / `topBid`, in order to be fully deterministic ordering
- Attribute filtering won't be able to use index, but we should still make sure it is performant (ie narrow down to the small number of matching tokens using indexes, then sort)

**Comment by dikkeduif** [comment]
Deployed
