### ISSUE TITLE
Filter sales/transfers/owners by collection/attributes

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#210]

**Comment by georgeroman** [comment]
So, I added caching of attributes in the tokens table and the results are slightly better, although there are cases when filtering by attributes still times out:
- https://api.reservoir.tools/transfers/v2?collection=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d&attributes[Clothes]=Tanktop
- https://api.reservoir.tools/sales/v3?collection=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d&attributes[Background]=Purple

**Comment by georgeroman** [comment]
Filtering owners by attributes is done:
- https://api.reservoir.tools/owners/v1?collection=0x8d04a8c79ceb0889bdd12acdf3fa9d207ed3ff63&attributes[Attunement]=Attuned
