### ISSUE TITLE
Collection APIs updates

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#217]
**Change route for single collection API**

Route: `/collection/v1`
Filters: id / slug

**Add `primaryContract` to both APIs**

For now, we only support collections in the same contract anyway

**V2 Collections, with reduce fields**

- id
- tokenSetId
- primaryContract
- slug
- name
- image
- banner
- sampleImages
- tokenCount
- floorAskPrice
- topBidValue
- topBidMaker
- 1dayVolume
- allTimeVolume
- allTimeRank

**Comment by ptrwtts** [comment]
Also, let's make collections v2 API filterable by slug, in case someone wants faster lookup

**Comment by georgeroman** [comment]
This is done:
- https://api.reservoir.tools/collections/v2?slug=lootproject
- https://api.reservoir.tools/collections/v2
- https://api.reservoir.tools/collection/v1?slug=boredapeyachtclub
- https://api.reservoir.tools/collection/v1?id=0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d
