### ISSUE TITLE
Index Metadata for all tokens

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#219]
**1) Index all remaining collections** 

For this, we just need to run a job to do them all in bulk. George has a script i believe.

**2) Continuous indexing**

The challenge with is that when tokens are first minted, our metadata sources may not have fetched the metadata yet. Also, if we index as tokens are minted, we can't do bulk indexing. Here is a suggested system to start with:

- add support for getting single tokens via rarible (more generous rate limits)
- when a token is minted, trigger a job to fetch metadata via rarible in 5 minutes (allow time for rarible to index. we may need to test and find the right number for this)
- when a new contract is detected, immediately fetch collection metadata (better than nothing), but also trigger a job to refetch in 24 hours. this is because collection metadata (slug, image, etc) often changes within the first 24 hours of minting

**Comment by georgeroman** [comment]
For 1) here's the script I was using (you'll need to first export all unindexed collection ids to a `collections.txt` file, which can be easily done in a similar fashion to what's described here: https://dba.stackexchange.com/a/247102):
```bash
cat collections.txt | while IFS= read -r collection; do curl -X POST -H "Content-Type: application/json" -H "X-Admin-Api-Key: ${ADMIN_API_KEY}" -d "{\"method\":\"rarible\",\"collection\":\"${collection}\"}" https://api.reservoir.tools/admin/index-metadata; done
```

For 2) I already added support for indexing single tokens via Rarible and an associated job that triggers a metadata indexing for tokens as soon as they get indexed. So the only tweak that's needed is add the 5 minute delay to the corresponding jobs. Collection metadata fetching is also integrated, all that's left is just a delayed job to refetch the metadata after 24 hours from when the collection was deployed.

**Comment by ptrwtts** [comment]
Talked to George, and for this one it probably just makes sense for him to handle. Reassigning.

**Comment by ptrwtts** [comment]
As discussed, just do the back fill, and we'll create a separate task for continuous indexing
