### ISSUE TITLE
`attributes/static` API

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#235]
Similar to the `attributes/all` API, but also return the token ids that have each attribute.

```
"key": "Eye Color",
"kind": "string",
"values": [
{
  "value": "Black",
  "count": 13960,
  "tokens": [
    "2",
    "123",
    "9822"
  ]
},
```

The idea behind this API is that you can combine the static information around which token has which attributes with the dynamic pricing information from the `tokens/floor` API to do local processing.

**Comment by georgeroman** [comment]
This is done: https://api.reservoir.tools/collections/0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d/attributes/static/v1. Right now, there are no restrictions on which collections are supported, the API will just timeout after 10 seconds if the processing takes too long.
