### ISSUE TITLE
Reference tokens by combined contract:tokenId (to discuss)

### ISSUE THREAD

**Issue by ptrwtts** [reservoirprotocol/indexer-v3#61]
Instead of having APIs where you need to pass contract and token id as separate parameters, how do we feel about having them passed as a single combined parameter? 

For one, it can be confusing when reading the docs, because it's unclear if the API supports passing just a contract (this is partially the fault of that bug, but the point still stands).

It also just feels right. I don't think we have a single API that supports tokenId without contract. The ID for a token is always the combination. 

I still think we keep them separate in the response, this is just when making requests.

This effectively how Rarible [does it](https://ethereum-api.rarible.org/v0.1/doc#operation/getNftItemMetaById). Interestingly, they do it by context. If you're using the Ethereum API, you pass contract:tokenId. If you're using their Union API, it's chain:contract:tokenid. In some ways they are ahead of us in a similar process, and i'm sure there's logic to doing it this way.

**Comment by georgeroman** [comment]
This is done in v5.
